name: flutter_unified_messaging_example
description: Example app demonstrating Flutter Unified Messaging
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.8.1 <4.0.0'
  flutter: ">=3.8.1"

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase dependencies
  firebase_core: ^3.15.1
  
  # Navigation
  go_router: ^16.0.0
  
  # State management (optional - for Riverpod example)
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  
  # Local package
  flutter_unified_messaging:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Riverpod code generation
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5

flutter:
  uses-material-design: true
